// ALERT
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// REGISTRATION
export const REGISTER_SUCESS = 'REGISTER_SUCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

// USER LOADED
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

// LOGIN
export const LOGIN_SUCESS = 'LOGIN_SUCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS'

// PROFILE
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'
export const UPDATE_CONNECTION = 'UPDATE_CONNECTION'

//STATUS 
export const ADD_POST = 'ADD_POST'
export const GET_POST = 'GET_POST'
export const GET_POSTS = 'GET_POSTS'
export const UPDATE_LIKES = 'UPDATE_LIKES'
export const POST_ERROR = 'POST_ERROR'
export const DELETE_POST = 'DELETE_POST'
export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

//CREATE PROFILE
export const CREATE_PROFILE = 'CREATE_PROFILE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_SOCIAL_PROFILE = 'UPDATE_SOCIAL_PROFILE'
export const UPDATE_CONTACT_PROFILE = 'UPDATE_CONTACT_PROFILE'